fixup: include the baileys-version.json when compiling using tsc
This issue depends of this error below:

Error: Cannot find module '../Defaults/baileys-version.json'
Require stack:                                                                          - /root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/Utils/generics.js               - /root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/Utils/index.js                  - /root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/Defaults/index.js               - /root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/LegacySocket/index.js           - /root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/index.js                        - /root/xyzbot-md/index.js                                                                  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)           at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)                            at require (node:internal/modules/cjs/helpers:102:18)                                   at Object.<anonymous> (/root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:35:32)                                                                           at Module._compile (node:internal/modules/cjs/loader:1105:14)                           at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)             at Module.load (node:internal/modules/cjs/loader:981:32)                                at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',                                                               requireStack: [                                                                           '/root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/Utils/generics.js',              '/root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/Utils/index.js',                 '/root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/Defaults/index.js',              '/root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/LegacySocket/index.js',
    '/root/xyzbot-md/node_modules/@adiwajshing/baileys/lib/index.js',
    '/root/xyzbot-md/index.js'                                                            ]                                                                                     } uncaughtException